items/urls.py
from django.urls import path
from . import views
app_name = 'items'

urlpatterns = [
    path('saree/cotton',views.CategoryPage.as_view(),name = 'category'),
    path('cart/',views.CartPage.as_view(),name = 'cart'),
    path('update_cart/',views.CartUpdatePage.as_view(), name = 'update_cart'),
    path('checkout/',views.CheckoutPage.as_view(), name = 'checkout'),
]

yuvraj_silk/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views as home_view
from items import views as item_views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('items/', include('items.urls',namespace='items')),
    path('users/', include('users.urls',namespace='users')),
    path('',home_view.IndexPage.as_view(), name='home'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

items/models.py
from django.db import models
from users.models import User
from PIL import Image
from django.dispatch import receiver
from django.db.models.signals import post_delete,post_save,pre_save
# from gdstorage.storage import GoogleDriveStorage

# Define Google Drive Storage
# gd_storage = GoogleDriveStorage()

# Create your models here.

class Item(models.Model):
    name = models.CharField(max_length=40)
    image = models.ImageField(upload_to="items/images/", blank = True) #storage=gd_storage
    description = models.TextField(blank = True)
    original_cost = models.FloatField()
    revised_cost = models.FloatField()
    stock = models.PositiveIntegerField(default=0)
    sold = models.PositiveIntegerField(default=0)
    booked = models.PositiveIntegerField(default=0)
    category = models.CharField(choices=(('women','Women'),('men','Men'),('childrenboy','Children Boys'),('childrengirl','Children Girls')), max_length=20)
    subcategory = models.CharField(choices=(('saree','Saree'),('kurtis','Kurtis'),('pant','Pant'),('shirt','Shirt'),('top','Top'),('chudidhar','Chididhar'),('other','Other')), max_length=20)
    material_type = models.CharField(choices=(('cotton','Cotton'),('silk','Silk'),('wool','Wool'),('leather','Leather'),('jeans','Jeans'),('other','Other')), max_length=20)
    newly_arrived = models.BooleanField(default=True)

    # def save(self, *args, **kwargs):
    #     super().save(*args, **kwargs)
    #     img = Image.open(self.image.path)
    #
    #     output_size = (260,300)
    #     img = img.resize(output_size)
    #     img.save(self.image.path)

class Cart(models.Model):

    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='carts')
    item = models.ForeignKey(Item, on_delete=models.CASCADE, related_name='carts')
    item_quantity = models.PositiveIntegerField(default=0)

    class Meta:
        unique_together = ('user', 'item',)


# Signals

# @receiver(post_delete, sender=Item)
# def submission_delete(sender, instance, **kwargs):
#     """
#     This function is used to delete attachments when a file object is deleted.
#     Django does not do this automatically.
#     """
#     instance.image.delete(False)

items/forms.py
from django import forms
from .models import Item

class ItemForm(forms.ModelForm):

    class Meta:
        model = Item
        exclude = ['sold','booked']

items/views.py
from django.shortcuts import render
from django.views import View
from .models import Item
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import Cart
from django.http import JsonResponse
from django.contrib import messages
# Create your views here.

class CategoryPage(View):
    def get(self, request):
        items = Item.objects.all()
        return render(request,'items/category.html',context = {'items':items})

class CartPage(LoginRequiredMixin,View):
    def get(self, request):
        carts = Cart.objects.filter(user=request.user).select_related('item','user')
        return render(request,'items/cart.html',{'carts':carts})

    def post(self, request):
        user = request.user
        item = int(request.POST.get('item'))
        item = Item.objects.get(pk=item)
        try:
            cart = Cart.objects.get(user=user, item=item)
            messages.warning(request,'Already added to the cart')
            return JsonResponse({
                'status':'Already added to the cart'
            })
        except:
            if item:
                messages.warning(request,'Successfully added to the cart')
                data = {
                    'status':'success'
                }
                quantity = 1
                cart = Cart.objects.create(user = user, item = item, item_quantity = quantity)
                cart.save()
                return JsonResponse(data)

class CartUpdatePage(LoginRequiredMixin,View):
    def post(self, request):
        pk = request.POST.get('pk')
        value = int(request.POST.get('value'))
        cart = Cart.objects.get(pk=pk)
        if value:
            cart.item_quantity = value
            cart.save()
        else:
            cart.delete()
        return JsonResponse({
                'status':'success'
        })

class CheckoutPage(LoginRequiredMixin, View):
    def get(self, request):
        carts = Cart.objects.filter(user=request.user).select_related('item','user')
        total_cost = 0
        for i in carts:
            total_cost += i.item_quantity * i.item.revised_cost
        context = {'carts':carts, 'total_cost':total_cost}
        return render(request,'items/checkout.html', context)

items/templates/items/cart.html
{% extends 'base.html' %}
{% load static %}
{% load cache %}
{% load cart_tags %}

{% block css_style %}
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{% static 'assets/css/cart.css' %}" media="screen" title="no title" charset="utf-8">
    <style>
        .empty_cart{
            font-size:35px;
        }
    </style>
{% endblock %}
{% block content %}
    <div class="shopping-cart">
      <!-- Title -->
      <div class="title">
        Shopping Bag
      </div>

      <!-- Product #1 -->
       <div class="container-fluid">
      <div class="col-md-12">
      <div class="row">
      {% for cart in carts %}

      <div class="item" id="cart_item-{{cart.id}}">
        <div class="buttons">
          <span class="delete-btn"></span>
          <span class="like-btn"></span>
        </div>

        <div class="image">
          <img src="{{ cart.item.image.url }}" alt="" style="height:75px; width:65px;" />
        </div>

        <div class="description">
          <span>{{ cart.item.name }}</span>
          <span></span>
        </div>

        <div class="quantity">
          <button class="plus-btn" id="{{ cart.pk }}" type="button" name="button">
            <img src="{% static 'assets/img/cart/plus.svg' %}" alt="" />
          </button>
          <input type="text" name="name" value="{{ cart.item_quantity }}">
          <button class="minus-btn" id="{{ cart.pk }}" type="button" name="button">
            <img src="{% static 'assets/img/cart/minus.svg' %}" alt="" />
          </button>
        </div>

        <div class="total-price">Rs. {% multiplier cart.item_quantity cart.item.revised_cost %}</div>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
      <div class="remove-button"><button type="button" id="{{ cart.pk }}" class="delete-btn" style="background-color:red; width:100%; font-color:white;" name="button">Remove</button></div>
    </div>

      {% empty %}
      <div class="item">
          <div class="empty_cart">
              No Item in Cart
          </div>
        </div>
      {% endfor %}
      </div>
      </div>
      </div>
    </div>
    {% if carts %}
        <a href="{% url 'items:checkout' %}" style="padding-left:25%;padding-right:25%;"><button type="button" class="delete-btn" style="font-size:200%; background-color:red; height:10%; width:50%; font-color:white;" name="button">Checkout</button></a>
    {% else %}
        <a href="#" style="padding-left:25%;padding-right:25%;"><button type="button" class="delete-btn" style="font-size:200%; background-color:red; height:10%; width:50%; font-color:white;" name="button" onclick="alert('Empty Cart');">Checkout</button></a>
    {% endif %}
{% endblock %}
    {% block scripting %}
    <script src="https://code.jquery.com/jquery-2.2.4.js" charset="utf-8"></script>
    <script type="text/javascript">
      $('.minus-btn').on('click', function(e) {
    		e.preventDefault();
    		var $this = $(this);
    		var $input = $this.closest('div').find('input');
    		var value = parseInt($input.val());
            var pk = $(this).closest(".minus-btn").attr("id");
    		if (value > 1) {
    			value = value - 1;
    		} else {
    			value = 0;
    		}
            $.ajax({
                url: '{% url "items:update_cart" %}',
                data: {
                  'pk': pk,
                  'value':value,
                  'remove':0,
                  csrfmiddlewaretoken: '{{ csrf_token }}'
                },
                dataType: 'json',
                type:'POST',
                success: function (data) {
                    location.reload();
                }
              });
        $input.val(value);

    	});

        $('.delete-btn').on('click', function(e) {
            var pk = $(this).closest(".delete-btn").attr("id");
              $.ajax({
                  url: '{% url "items:update_cart" %}',
                  data: {
                    'pk': pk,
                    'value':0,
                    csrfmiddlewaretoken: '{{ csrf_token }}'
                  },
                  dataType: 'json',
                  type:'POST',
                  success: function (data) {
                      $("#cart_item-"+pk).hide();
                  }
                });
      	});

    	$('.plus-btn').on('click', function(e) {
    		e.preventDefault();
    		var $this = $(this);
    		var $input = $this.closest('div').find('input');
    		var value = parseInt($input.val());
            var pk = $(this).closest(".plus-btn").attr("id");
    		if (value < 100) {
      		value = value + 1;
            }
            else {
                value =100;
            }
            $.ajax({
                url: '{% url "items:update_cart" %}',
                data: {
                  'pk': pk,
                  'value':value,
                  'remove':0,
                  csrfmiddlewaretoken: '{{ csrf_token }}'
                },
                dataType: 'json',
                type:'POST',
                success: function (data) {
                    location.reload();
                }
              });
    		$input.val(value);
    	});

      $('.like-btn').on('click', function() {
        $(this).toggleClass('is-active');
      });
    </script>
  {% endblock %}

items/templates/items/category.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <section class="product_list section_padding">
        <div class="container">
            <div class="row">

                <div class="col-md-12">
                    <div class="product_list">
                        <div class="row">
                            {% for item in items %}
                                <div class="col-md-3 col-md-3">
                                    <div class="single_product_item">
                                        <center><img src="{{ item.image.url }}" alt="" class="img-fluid" ></center>
                                        <center><h3><a href="single-product.html">{{ item.name }}</a></h3></center>
                                       <div class="price">
                                                <center><ul style="font-size:30px;">
                                                    <li>${{ item.revised_cost }}</li>
                                                </ul></center>
                                       </div><br>
                                       <div class="hero__btn" data-animation="fadeInRight" data-delay="1s">
                                           <center><button type="button" name="button" id="{{item.pk}}" class="btn hero-btn cart_button">Add To Cart</button></center>
                                       </div>
                                       </div>
                                </div>
                            {% endfor %}
                        </div>
                        <div class="load_more_btn text-center">
                            <a href="#" class="btn_3">Load More</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- product list part end-->

    <!-- client review part here -->
        <!-- client review part end -->

    <!-- Shop Method Start-->
    <!-- Shop Method End-->

    <!-- subscribe part here -->
    <section class="subscribe_part section_padding">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-lg-8">
                    <div class="subscribe_part_content">
                        <h2>Get promotions & updates!</h2>
                        <p>Seamlessly empower fully researched growth strategies and interoperable internal or “organic” sources credibly innovate granular internal .</p>
                        <div class="subscribe_form">
                            <input type="email" placeholder="Enter your mail">
                            <a href="#" class="btn_1">Subscribe</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- subscribe part end -->
{% endblock %}

items/templates/items/checkout.html
{% extends 'base.html' %}

{% block css_style %}
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<style>
body {
  font-family: Arial;
  font-size: 17px;
  padding: 8px;
  width: 99%;
}

* {
  box-sizing: border-box;
}

.row {
  display: -ms-flexbox; /* IE10 */
  display: flex;
  -ms-flex-wrap: wrap; /* IE10 */
  flex-wrap: wrap;
  margin: 0 -16px;
}

.col-25 {
  -ms-flex: 25%; /* IE10 */
  flex: 25%;
}

.col-50 {
  -ms-flex: 50%; /* IE10 */
  flex: 50%;
}

.col-75 {
  -ms-flex: 75%; /* IE10 */
  flex: 75%;
}

.col-25,
.col-50,
.col-75 {
  padding: 0 16px;
}

.container {
  background-color: #f2f2f2;
  padding: 5px 20px 15px 20px;
  border: 1px solid lightgrey;
  border-radius: 3px;
}

input[type=text] {
  width: 100%;
  margin-bottom: 20px;
  padding: 12px;
  border: 1px solid #ccc;
  border-radius: 3px;
}

label {
  margin-bottom: 10px;
  display: block;
}

.icon-container {
  margin-bottom: 20px;
  padding: 7px 0;
  font-size: 24px;
}

.btn {
  background-color: #4CAF50;
  color: white;
  padding: 12px;
  margin: 10px 0;
  border: none;
  width: 100%;
  height: 40px;
  border-radius: 3px;
  cursor: pointer;
  font-size: 17px;
}

.btn:hover {
  background-color: #45a049;
}

a {
  color: #2196F3;
}

hr {
  border: 1px solid lightgrey;
}

span.price {
  float: right;
  color: grey;
}

/* Responsive layout - when the screen is less than 800px wide, make the two columns stack on top of each other instead of next to each other (also change the direction - make the "cart" column go on top) */
@media (max-width: 800px) {
  .row {
    flex-direction: column-reverse;
  }
  .col-25 {
    margin-bottom: 20px;
  }
}
</style>
{% endblock %}

{% block content %}
<h2 style="text-align:center;">Checkout Form</h2>
<div class="row">
  <div class="col-75">
    <div class="container">
      <form action="">

        <div class="row">
          <div class="col-50">
            <h3>Billing Address</h3>
            <label for="fname"><i class="fa fa-user"></i> Full Name</label>
            <input type="text" id="fname" name="firstname" value="{{ user.get_full_name }}" placeholder="{{ user.get_full_name }}">
            <label for="email"><i class="fa fa-envelope"></i> Email</label>
            <input type="text" id="email" name="email "value="{{ user.email }}" placeholder="{{ user.email }}">
            <label for="adr"><i class="fa fa-address-card-o"></i> Address</label>
            <input type="text" id="adr" name="address" placeholder="542 W. 15th Street">
            <label for="city"><i class="fa fa-institution"></i> City</label>
            <input type="text" id="city" name="city" placeholder="New York">

            <div class="row">
              <div class="col-50">
                <label for="state">State</label>
                <input type="text" id="state" name="state" placeholder="NY">
              </div>
              <div class="col-50">
                <label for="zip">Zip</label>
                <input type="text" id="zip" name="zip" placeholder="10001">
              </div>
            </div>
          </div>

          <div class="col-50">
            <h3>Payment</h3>
            <label for="fname">Accepted Cards</label>
            <div class="icon-container">
              <i class="fa fa-cc-visa" style="color:navy;"></i>
              <i class="fa fa-cc-amex" style="color:blue;"></i>
              <i class="fa fa-cc-mastercard" style="color:red;"></i>
              <i class="fa fa-cc-discover" style="color:orange;"></i>
            </div>
            <label for="cname">Name on Card</label>
            <input type="text" id="cname" name="cardname" placeholder="John More Doe">
            <label for="ccnum">Credit card number</label>
            <input type="text" id="ccnum" name="cardnumber" placeholder="1111-2222-3333-4444">
            <label for="expmonth">Exp Month</label>
            <input type="text" id="expmonth" name="expmonth" placeholder="September">
            <div class="row">
              <div class="col-50">
                <label for="expyear">Exp Year</label>
                <input type="text" id="expyear" name="expyear" placeholder="2018">
              </div>
              <div class="col-50">
                <label for="cvv">CVV</label>
                <input type="text" id="cvv" name="cvv" placeholder="352">
              </div>
            </div>
          </div>

        </div>
        <label>
          <input type="checkbox" checked="checked" name="sameadr"> Shipping address same as billing
        </label>
        <input type="submit" value="Continue to checkout" class="btn">
      </form>
    </div>
  </div>
  <div class="col-25">
    <div class="container">
      <h4>Cart <span class="price" style="color:black"><i class="fa fa-shopping-cart"></i> <b>4</b></span></h4>
      {% for cart in carts %}
          <p><a href="#">{{ cart.item.name }}</a> <span class="price">Rs. <b>{{ cart.item.revised_cost }}</b> X <b>{{ cart.item_quantity }}</b></span></p>
      {% endfor %}
      <hr>
      <p>Total <span class="price" style="color:black"><b>Rs. {{ total_cost }}</b></span></p>
    </div>
  </div>
</div>
{% endblock %}